groups:

  - name: base
    rules:

        # Alert is critical all the time. Query alertmanager API and
        # check if its firing to ensure your alerting pipeline works as intended
      - alert: DeadMansSwitch
        expr: vector(1)
        labels:
          priority: P1
        annotations:
          summary: "ensures that the entire alerting pipeline is functional - if not firing prometheus might have a problem"

        # Alert that fires once a week during a fixed timeframe to test
        # your alerting pipeline. If there is no alert on monday,
        # you might have a problem
      - alert: WeeklyTestalert
        expr: day_of_week() == 1 and hour() == 8 and minute() < 20
        for: 1m
        labels:
          priority: P1
        annotations:
          summary: "this weekly test alert notification shows that the alerting pipeline is functional"
