groups:

  - name: apt
    rules:

      - alert: AptRebootRequired
        expr: "apt_reboot_required == 1"
        for: 1m
        labels:
          priority: P3
        annotations:
          summary: "reboot required"

      - alert: AptSecurityUpgrades
        expr: "apt_security_upgrades >= 1"
        for: 36h
        labels:
          priority: P2
        annotations:
          summary: "{{ $value }} apt security upgrades to install"
