groups:
  - name: opensmtpd
    rules:

      - alert: OpenSmtpdQueue
        expr: "opensmtpd_stat_scheduler_envelope >= 1"
        for: 2h
        labels:
          priority: P4
        annotations:
          summary: "{{ $value }} undeliverable emails in queue"

      - alert: OpenSmtpdRunning
        expr: "(opensmtpd_service_mda == 0) or (opensmtpd_service_mta == 0) or (opensmtpd_service_smtp == 0)"
        for: 2h
        labels:
          priority: P4
        annotations:
          summary: "opensmtpd component not running (check smtpctl show status)"
