groups:

  - name: shorewall
    rules:

      - alert: ShorewallRunning
        expr: "shorewall_running == 0"
        for: 1s
        labels:
          priority: P1
        annotations:
          summary: "shorewall is not running"

      - alert: Shorewall6Running
        expr: "shorewall6_running == 0"
        for: 1s
        labels:
          priority: P1
        annotations:
          summary: "shorewall6 is not running"
