groups:

  - name: ssl-certificate
    rules:

      - alert: SslCertificateExpirationDays14
        expr: "( ssl_certificate_expiration_seconds / 60 / 60 / 24 ) < 14"
        for: 5m
        labels:
          priority: P2
        annotations:
          summary: "ssl certificate {{ $labels.path }} is expiring in less than 14 days (current value: {{ $value }} days)"

      - alert: SslCertificateExpirationDays3
        expr: "( ssl_certificate_expiration_seconds / 60 / 60 / 24 ) < 3"
        for: 5m
        labels:
          priority: P1
        annotations:
          summary: "ssl certificate {{ $labels.path }} is expiring in less than 3 days (current value: {{ $value }} days)"
