groups:

  - name: system-priority
    rules:

        # Simply states the system priority
      - alert: SystemPriority
        expr: system_priority > 0
        annotations:
          summary: "only states the system priority"
