groups:

  - name: systemd
    rules:

      - alert: SystemdUnitFailed
        expr: node_systemd_unit_state{state="failed"} == 1
        for: 10m
        labels:
          priority: P3
          service: "{{ $labels.name }}"
        annotations:
          summary: "systemd unit {{ $labels.name }} failed"

      - alert: SystemdInactiveTimers
        expr: >-
          node_systemd_unit_state
            {name=~ ".*timer",
             state="inactive",
             name!="systemd-readahead-done.timer"
            }
          == 1
        for: 10m
        labels:
          priority: P4
          service: "{{ $labels.name }}"
        annotations:
          summary: "systemd timers {{ $labels.name }} is inactive"

#      - alert: SystemdSystemRunning
#        expr: node_systemd_system_running == 0
#        for: 10m
#        labels:
#          priority: P3
#        annotations:
#          summary: "systemd reports degraded"

#      - alert: SystemdTimerNotExecuted
#        expr: >-
#          (time() -
#          node_systemd_timer_last_trigger_seconds
#            {name!="systemd-readahead-done.timer"}
#          )
#          / 60 / 60 / 24 > 3
#        for: 10m
#        labels:
#          priority: P4
#        annotations:
#          summary: "systemd timer {{ $labels.name }} did not run for {{ $value }} days"
