- name: "grafana {{ prometheus_grafana_version }} install deb"
  apt:
    deb: "https://dl.grafana.com/oss/release/grafana_{{ prometheus_grafana_version }}_amd64.deb"
    state: present
  notify:
    - reload systemd daemon
    - restart grafana server

- name: "grafana {{ prometheus_grafana_version }} template config file"
  template:
    src: templates/etc/grafana/grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: root
    group: grafana
    mode: 0640
  notify: restart grafana server

- name: "grafana {{ prometheus_grafana_version }} fix systemd config file"
  template:
    src: templates/lib/systemd/system/grafana-server.service.j2
    dest: /lib/systemd/system/grafana-server.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd daemon
    - restart grafana server

- name: "grafana {{ prometheus_grafana_version }} create prometheus-server datasource"
  grafana_datasource:
    name: "prometheus-server"
    grafana_url: "http://127.0.0.1:10002"
    grafana_api_key: "eyJrIjoiclQ2MGNQdDZTM0c3Q2l0UDdwQnpONFRINWw0UUx3Y1oiLCJuIjoiYW5zaWJsZTIiLCJpZCI6MX0="
    org_id: "1"
    ds_type: "prometheus"
    ds_url: "http://127.0.0.1:9090/prometheus"
    is_default: True

- name: "grafana {{ prometheus_grafana_version }} create prometheus-downsampling datasource"
  grafana_datasource:
    name: "prometheus-downsampling"
    grafana_url: "http://127.0.0.1:10002"
    grafana_api_key: "eyJrIjoiclQ2MGNQdDZTM0c3Q2l0UDdwQnpONFRINWw0UUx3Y1oiLCJuIjoiYW5zaWJsZTIiLCJpZCI6MX0="
    org_id: "1"
    ds_type: "prometheus"
    ds_url: "http://127.0.0.1:9091/downsampling"
    is_default: False
