- name: "prometheus-downsampling {{ prometheus_server_version }} create prometheus-downsampling group"
  group:
    name: prometheus-downsampling
    system: True
    gid: 133

- name: "prometheus-downsampling {{ prometheus_server_version }} create prometheus-downsampling user"
  user:
    name: prometheus-downsampling
    system: True
    home: /var/lib/prometheus-downsampling
    shell: /bin/false
    group: prometheus-downsampling
    uid: 133

- name: "prometheus-downsampling {{ prometheus_server_version }} create directories"
  file:
    state: directory
    path: "/etc/prometheus-downsampling/rules.d"
    owner: prometheus-downsampling
    group: prometheus-downsampling
    mode: 0750

- name: "prometheus-downsampling {{ prometheus_server_version }} template prometheus.yml"
  template:
    src: templates/etc/prometheus-downsampling/prometheus.yml.j2
    dest: /etc/prometheus-downsampling/prometheus.yml
    owner: prometheus-downsampling
    group: prometheus-downsampling
    mode: 0640
  notify: restart prometheus downsampling

- name: "prometheus-downsampling {{ prometheus_server_version }} template systemd unit file"
  template:
    src: templates/etc/systemd/system/prometheus-downsampling.service.j2
    dest: /etc/systemd/system/prometheus-downsampling.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd daemon
    - restart prometheus downsampling
